[build]
  command = "npm run build"
  publish = "build"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  function = "auth"
  path = "/*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"